### ISSUE TITLE
seems it doesn't works with react-waterfall@4.0.0-beta.4 on react-native

### ISSUE THREAD

**Issue by danllach** [elisherer/react-waterfall-redux-devtools-middleware#4]
I have this code: 

```
import createStore from 'react-waterfall'
import reduxDevTools from 'react-waterfall-redux-devtools-middleware'

const config = {
  initialState: { count: 0 },
  actionsCreators: {
    increment: ({ count }) => ({ count: count + 1 }),
  }
}

export const { Provider, connect, actions } = createStore(config, reduxDevTools())
```

and get this error:

<img width="438" alt="screen shot 2018-07-13 at 11 00 45 am" src="https://user-images.githubusercontent.com/38475659/42698491-0f6def96-868c-11e8-8d28-46b190788694.png">

does support react-waterfall v4 ? or maybe I'm doing something wrong

**Comment by elisherer** [comment]
You don't need this in v4,
v4 has redux devtools capabilities already embedded.
this library is only for v3

**Comment by danllach** [comment]
Thanks for your answer 🤙🏼
